---
apiVersion: v1
kind: Service
metadata:
  name: catbox-0
spec:
  ports:
    - port: 6667
  selector:
    statefulset.kubernetes.io/pod-name: catbox-0
---
apiVersion: v1
kind: Service
metadata:
  name: catbox-1
spec:
  ports:
    - port: 6667
  selector:
    statefulset.kubernetes.io/pod-name: catbox-1
---
apiVersion: v1
kind: Service
metadata:
  name: catbox
spec:
  ports:
    - port: 7000
  selector:
    app: catbox
  type: LoadBalancer
  loadBalancerIP: 35.185.215.109
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catbox
spec:
  selector:
    matchLabels:
      app: catbox
  serviceName: catbox
  replicas: 2
  template:
    metadata:
      labels:
        app: catbox
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - catbox
              topologyKey: kubernetes.io/hostname
      containers:
        - name: catbox
          image: gcr.io/elite-vault-142205/catbox:1.11.1-2019-07-01-005
          command:
            - ./catbox
            - -conf
            - /etc/catbox/$(POD_NAME).conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 6667
            - containerPort: 7000
          resources:
            limits:
              memory: 150Mi
            requests:
              memory: 100Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/catbox
            - name: servers-config-volume
              mountPath: /etc/catbox-servers
            - name: certificate-volume
              mountPath: /etc/catbox-certificate
            - name: tls-key-volume
              mountPath: /etc/catbox-tls-key
      volumes:
        - name: config-volume
          configMap:
            name: catbox-config
        - name: servers-config-volume
          secret:
            secretName: servers-config
        - name: certificate-volume
          configMap:
            name: certificate
        - name: tls-key-volume
          secret:
            secretName: tls-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catbox-config
data:
  catbox-0.conf: |-
    listen-port-tls  = 7000
    certificate-file = /etc/catbox-certificate/certificate.pem
    key-file         = /etc/catbox-tls-key/key.pem
    servers-config   = /etc/catbox-servers/servers.conf
    server-name      = irc0.summercat.com
    ts6-sid          = 000
  catbox-1.conf: |-
    listen-port-tls  = 7000
    certificate-file = /etc/catbox-certificate/certificate.pem
    key-file         = /etc/catbox-tls-key/key.pem
    servers-config   = /etc/catbox-servers/servers.conf
    server-name      = irc1.summercat.com
    ts6-sid          = 100
