---
apiVersion: v1
kind: Service
metadata:
  name: catbox-0
spec:
  ports:
    - port: 6667
  selector:
    statefulset.kubernetes.io/pod-name: catbox-0
---
apiVersion: v1
kind: Service
metadata:
  name: catbox-1
spec:
  ports:
    - port: 6667
  selector:
    statefulset.kubernetes.io/pod-name: catbox-1
---
apiVersion: v1
kind: Service
metadata:
  name: catbox
spec:
  ports:
    - port: 7000
  selector:
    app: catbox
  type: LoadBalancer
  loadBalancerIP: 34.83.184.224
  externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catbox
spec:
  selector:
    matchLabels:
      app: catbox
  serviceName: catbox
  replicas: 2
  template:
    metadata:
      labels:
        app: catbox
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - catbox
              topologyKey: kubernetes.io/hostname
      containers:
        - name: catbox
          image: gcr.io/elite-vault-142205/catbox:1.13.0-2019-07-08-000
          command:
            - ./catbox
            - -conf
            - /etc/catbox/$(POD_NAME).conf
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 6667
            - containerPort: 7000
          resources:
            limits:
              memory: 150Mi
            requests:
              memory: 100Mi
          # I want to delay the container being considered ready so that it has
          # a chance to link to old instances before they're terminated (during
          # updates).
          readinessProbe:
            exec:
              command:
                - /bin/true
            initialDelaySeconds: 10
          volumeMounts:
            - name: config-volume
              mountPath: /etc/catbox
      volumes:
        - name: config-volume
          secret:
            secretName: irc-config
