---
apiVersion: v1
kind: Service
metadata:
  name: irc
  labels:
    app: catbox
spec:
  ports:
    # TODO: 7000 instead
    - port: 6667
      name: plaintext
    #- port: 7000
    #  name: secure
  # Kubernetes docs say the Service must be headless (clusterIP: None) for a StatefulSet, but that's
  # apparently not true?
  selector:
    app: catbox
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catbox
spec:
  selector:
    matchLabels:
      app: catbox
  serviceName: catbox
  # TODO: Add more
  replicas: 1
  template:
    metadata:
      labels:
        app: catbox
    spec:
      containers:
        - name: catbox
          image: gcr.io/elite-vault-142205/catbox:1.11.1-2019-07-01-001
          command: ['/catbox', '-conf',  '/etc/catbox/catbox.conf']
          ports:
            - containerPort: 6667
              name: plaintext
            - containerPort: 7000
              name: secure
          volumeMounts:
            - name: config-volume
              mountPath: /etc/catbox
      volumes:
        - name: config-volume
          configMap:
            name: catbox-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catbox-config
data:
  catbox.conf: |-
    # TODO
